"""不依赖 IDA 的 Supervisor 公共 API。"""

from ida_re_mcp.supervisor.artifacts import (
    ArtifactChunk,
    ArtifactFileInput,
    ArtifactGarbageCollectionResult,
    ArtifactMetadata,
    ArtifactStore,
    ChunkedArtifact,
    artifact_uri,
    parse_artifact_uri,
)
from ida_re_mcp.supervisor.errors import (
    AnalysisRetryUnavailableError,
    ArtifactIntegrityError,
    ArtifactNotFoundError,
    InvalidIdentifierError,
    OperationNotFoundError,
    OperationStateError,
    RevisionConflictError,
    RevisionNotFoundError,
    StagingIntegrityError,
    StorageCorruptionError,
    SupervisorError,
    WorkspaceNotFoundError,
)
from ida_re_mcp.supervisor.operations import (
    OperationCoordinator,
    OperationFailure,
    OperationSnapshot,
    OperationState,
)
from ida_re_mcp.supervisor.storage import StorageUsage, SupervisorStorage
from ida_re_mcp.supervisor.workspaces import (
    AnalysisOutcome,
    ColdValidationReceipt,
    GarbageCollectionResult,
    ImageIdentity,
    RevisionCheckout,
    RevisionSnapshot,
    RevisionStaging,
    WorkspaceRegistry,
    WorkspaceSnapshot,
    hash_staging_payload,
)

__all__ = [
    "AnalysisOutcome",
    "AnalysisRetryUnavailableError",
    "ArtifactChunk",
    "ArtifactFileInput",
    "ArtifactGarbageCollectionResult",
    "ArtifactIntegrityError",
    "ArtifactMetadata",
    "ArtifactNotFoundError",
    "ArtifactStore",
    "ChunkedArtifact",
    "ColdValidationReceipt",
    "GarbageCollectionResult",
    "ImageIdentity",
    "InvalidIdentifierError",
    "OperationCoordinator",
    "OperationFailure",
    "OperationNotFoundError",
    "OperationSnapshot",
    "OperationState",
    "OperationStateError",
    "RevisionCheckout",
    "RevisionConflictError",
    "RevisionNotFoundError",
    "RevisionSnapshot",
    "RevisionStaging",
    "StagingIntegrityError",
    "StorageCorruptionError",
    "StorageUsage",
    "SupervisorError",
    "SupervisorStorage",
    "WorkspaceNotFoundError",
    "WorkspaceRegistry",
    "WorkspaceSnapshot",
    "artifact_uri",
    "hash_staging_payload",
    "parse_artifact_uri",
]
